[
  {
    authors: ["Ndueche, Peter Izuchukwu", "Ven. Dr. J.K.J Onuora"],
    downloads: 0,
    name: "Effect of IFRS Adoption on Performance of Listed Deposit Money Banks in Nigeria",
    pages: "1-19",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/NDuche+and+Ven+jkj+paper.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Alhaji Thomas", "Egbo Anthonia Chinoyelum"],
    downloads: 0,
    name: "Influence of Rehabilitation Counselling on Prisons Inmates in Nigeria",
    pages: "20-26",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Egbo+Anthonia.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Onyekezie Chizoba Juliet"],
    downloads: 0,
    name: "Insecurity in the School Environment in the Area of Inclusive Education",
    pages: "27-39",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Onyekezie+Juliet.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Egbo, Anthonia Chinonyelum (Ph.D)", "Ogenyi Andrew Ejah"],
    downloads: 0,
    name: "Concept on Counselling Parents with Albino Children",
    pages: "40-52",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Ogenyi+Andrew+and+Egbo+A.C.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Chukwuemeka Obiageli Angela"],
    downloads: 0,
    name: "Health and Counselling with Focus on HIV/AIDS",
    pages: "53-63",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Chukwuemaka+Obiageli+Angela.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Uchenna Adoctus Maduekwe"],
    downloads: 0,
    name: "Counselling Strategies for Managing Disciplinary Problems Among Secondary School Students",
    pages: "64-74",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Uchenna+Adoctus+Madukwe.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Igwesi Faith Nebechi"],
    downloads: 0,
    name: "Reducing the Negative Effects of Single Parenting on Secondary School Students through Guidance Services",
    pages: "75-80",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Igwesi+faith.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Okonji Ndidiamaka Emilia"],
    downloads: 0,
    name: "The Role of Guidance and Counselling in Ebonyi State: Advancement and Challenges",
    pages: "81-88",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Okonji+Ndidiamaka.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Edo Chibuogwu U."],
    downloads: 0,
    name: "Marriage and Counselling",
    pages: "89-103",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Edo+Chibuogwu.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Ezeudu, N.M."],
    downloads: 0,
    name: "Maladaptive Behaviour in Adolescents and Post-Adolescents Implications for Counselling",
    pages: "104-110",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Ezeudu+N.M.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Ugwu, Chidimma Priscilla"],
    downloads: 0,
    name: "Improving Students' Academic Performace through Effective Guidance and Counselling Services",
    pages: "111-118",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Ugwu+Chidimma.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Ozor, Tobias Obiora", "Umezurike, Juliet Chinelo"],
    downloads: 0,
    name: "Job Satisfaction as a Predictor of Organization Commitment Among Company Workers",
    pages: "119-130",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Ozor%2C+Tobias.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Ani, Nnenna Glory"],
    downloads: 0,
    name: "Counsellors' Perception of Counselling Strategies for Curbing Examination Malpractice in Secondary Schools in Enugu State",
    pages: "131-147",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Ani+Nnenna.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Anochili Akunna A."],
    downloads: 0,
    name: "Current Issues and Problems in Marriage Counselling Practices",
    pages: "148-159",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Anochili+Akunna.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Dr. John O. Odo"],
    downloads: 0,
    name: "Guidance Needs of New Students in State Secondary Schools in Udenu Local Government Area of Enugu State",
    pages: "160-166",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Dr.+John+Odo.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Egbo, Chinonye Emmanuella"],
    downloads: 0,
    name: "Impact of Poverty on the Academic Performance of Senior Secondary School Students in Enugu South Local Government Area of Enugu State",
    pages: "167-175",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Egbo+Chinonyelum+Emmanuella.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Dr. Eke N. Ukpai", "Mrs Ijeoma J. Chukwuemeka-Nworu"],
    downloads: 0,
    name: "School Management Strategies for Enhancing the Provision and Utilization of Counselling Services in Secondary Schools in Anambra State",
    pages: "176-192",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Dr+Eke+Ukpai.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Edeh Ephraim Onyekachi"],
    downloads: 0,
    name: "Insecurity in School Environment",
    pages: "193-200",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Edeh+Ephraim.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Dr Nweze, Bernardine, Ngozi"],
    downloads: 0,
    name: "Assessment of the Qualities of NEEM Oil as An Alternative Material to Palm Kernel Oil in Soap Production in Schools",
    pages: "201-212",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Dr+Nweze+B.N.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Asogwa, Solomon C.", "Aneke Ogechukwu C."],
    downloads: 0,
    name: "Instances of Conflict in Schools and How They Can Be Resolved",
    pages: "213-222",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Asogwa+and+Aneke.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },
  {
    authors: ["Dr. John O. Odo"],
    downloads: 0,
    name: "Academic Performace Dishonest and Use of Cell-Phone Syndrome Among the Secondary School Students in Enugu State",
    pages: "223-232",
    pdfUrl: "https://esut-journal-bucket.s3.eu-north-1.amazonaws.com/Dr.+J.O.+Odo.pdf",
    publishDate: "June 2021",
    views: 0,
    volumeId: "jx7a42gw5zrnh652vcfjm2efrs7st3e6",
  },

]
